# Generated by Django 4.2.1 on 2023-05-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='source',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(),
        ),
    ]
