# Generated by Django 4.2.1 on 2023-05-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
