# Generated by Django 4.2.1 on 2023-05-29 21:06

from django.db import migrations, models
import videos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_upload_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to='uploads', validators=[videos.validators.validate_video_extension, videos.validators.validate_video_size, videos.validators.validate_video_duration]),
        ),
    ]
