# Generated by Django 4.2.2 on 2023-07-20 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_description'),
        ('videos', '0005_alter_upload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='user',
        ),
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
        migrations.AddField(
            model_name='upload',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='profiles.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='profiles.profile'),
            preserve_default=False,
        ),
    ]
