# Generated by Django 4.2.3 on 2023-08-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_alter_video_source_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='first_frame',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
