# Generated by Django 4.2.3 on 2023-10-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_video_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='filename',
            field=models.CharField(default='a.mp4', max_length=100),
            preserve_default=False,
        ),
    ]
