# Generated by Django 4.2.3 on 2023-12-28 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_description'),
        ('videos', '0016_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mentioned_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentioned_in_comments', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='mentioned_profile_username',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
