# Generated by Django 4.2.3 on 2024-02-09 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_description'),
        ('videos', '0018_comment_popularity_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Unwanted commercial content or spam'), ('pornography', 'Pornography or sexually explicit material'), ('child_abuse', 'Child abuse'), ('hate_speech', 'Hate speech or graphic violence'), ('terrorism', 'Promotes terrorism'), ('harassment', 'Harassment or bullying'), ('suicide', 'Suicide or self injury'), ('misinformation', 'Misinformation')], max_length=20)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='videos.comment')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reports', to='profiles.profile')),
            ],
        ),
    ]
