# Generated by Django 5.0.2 on 2024-03-04 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_description'),
        ('videos', '0020_savedvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('sex', 'Sexual content'), ('violence', 'Violent or repulsive content'), ('hate', 'Hateful or abusive content'), ('harassment', 'Harassment or bullying'), ('danger', 'Harmful or dangerous acts'), ('misinformation', 'Misinformation'), ('child_abuse', 'Child abuse'), ('terrorism', 'Promotes terrorism'), ('spam', 'Spam or misleading')], max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_reports', to='profiles.profile')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='videos.video')),
            ],
        ),
    ]
