# Generated by Django 5.0.4 on 2024-05-15 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('videos', '0024_alter_savedvideo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.notification')),
                ('type', models.CharField(choices=[('comment', 'Comment')], default='comment', max_length=50)),
                ('subtype', models.CharField(choices=[('like', 'Like'), ('reply', 'Reply')], max_length=50)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_comment', to='videos.comment')),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_reply', to='videos.comment')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
            bases=('notifications.notification',),
        ),
        migrations.CreateModel(
            name='VideoNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.notification')),
                ('type', models.CharField(choices=[('video', 'Video')], default='video', max_length=50)),
                ('subtype', models.CharField(choices=[('upload_processed', 'Upload Processed'), ('comment', 'Comment'), ('followed_profile_video', 'Followed Profile Video')], max_length=50)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.comment')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
            bases=('notifications.notification',),
        ),
    ]
