# Generated by Django 5.0.4 on 2024-05-15 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('profiles', '0003_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.notification')),
                ('type', models.CharField(choices=[('profile', 'Profile')], default='profile', max_length=50)),
                ('subtype', models.CharField(choices=[('new_follower', 'New Follower')], max_length=50)),
                ('related_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            bases=('notifications.notification',),
        ),
    ]
