version: "3"
services:
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 16379:6379

  worker:
    image: zhenghaoz/gorse-worker
    restart: unless-stopped
    ports:
      - 18089:8089
    command: >
      --master-host master --master-port 8086 
      --http-host 0.0.0.0 --http-port 8089
      --log-path /var/log/gorse/worker.log 
      --cache-path /var/lib/gorse/worker_cache.data
    volumes:
      - gorse_log:/var/log/gorse
      - worker_data:/var/lib/gorse
    depends_on:
      - master

  server:
    image: zhenghaoz/gorse-server
    restart: unless-stopped
    ports:
      - 18087:8087
    command: >
      --master-host master --master-port 8086 
      --http-host 0.0.0.0 --http-port 8087
      --log-path /var/log/gorse/server.log 
      --cache-path /var/lib/gorse/server_cache.data
    volumes:
      - gorse_log:/var/log/gorse
      - server_data:/var/lib/gorse
    depends_on:
      - master

  master:
    image: zhenghaoz/gorse-master
    restart: unless-stopped
    ports:
      - 18086:8086
      - 18088:8088
    environment:
      GORSE_CACHE_STORE: redis://redis:6379/3
      GORSE_DATA_STORE: mysql://root:FireIsComing!@tcp(host.docker.internal:3306)/test_gorse
    command: >
      -c /etc/gorse/config.toml 
      --log-path /var/log/gorse/master.log 
      --cache-path /var/lib/gorse/master_cache.data
    volumes:
      - ./gorse/config.toml:/etc/gorse/config.toml
      - gorse_log:/var/log/gorse
      - master_data:/var/lib/gorse
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  worker_data:
  server_data:
  master_data:
  gorse_log:
