# Generated by Django 4.2.3 on 2024-01-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_keys', models.JSONField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
